name: Test

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-setup

      - name: Test
        run: pnpm lint:css && pnpm lint:js && pnpm check:types
